name: MineralPractice
version: .dev1
author: Jaiden
main: gg.mineral.practice.PracticePlugin
description: Mineral Practice Plugin!
depend: [ packetevents, MineralBot, MineralDatabaseAPI, NametagAPI ]
softdepend: [ KnockbackSync, Apollo-Bukkit ]